[project]
name = "somejson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.11.0",
    "fastapi[standard]>=0.119.0",
]
